### PR TITLE
added locize and localistars to "Who uses it"

### PR DESCRIPTION
**Pull request by adrai**

### CODE REVIEW

**Comment by adrai** [comment]
Is this ok for you?

**Comment by adrai** [comment]
@valeriansaliou is there a problem with this? Do I need to change something?

**Comment by valeriansaliou** [comment]
It’s all right. I will process this when I will have further work done on the lib later this week.

**Comment by adrai** [comment]
thx for merging...
But may I ask why you removed localistars?

**Comment by valeriansaliou** [comment]
It's your agency, not an actual product. I can't agree on leaving it in the README front page for this reason.

**Comment by adrai** [comment]
fyi: it's not an agency... it's a SaaS platform which will extend locize... no agency...
we will release this in the next weeks: https://docs.locize.com/guides-tips-and-tricks/working-with-translators#coming-soon-localistars-service
But ok, for me if you can't agree on leaving it in the readme, no problem

**Pull request merged**
