### PR TITLE
Add detailed field to __buildSalesTaxContext

### PR DESCRIPTION
**Pull request by maktouch**
This is so we can generate Canadian invoices with this library. In Canada, you need to list individual amounts of taxes on the invoice because they are filed to different government bodies.

It passes jshint, and no tests are broken (this is purely additive). 

Hope we can get this merged. 

Merci!

### CODE REVIEW

**Comment by adrai** [comment]
Isn't this the same as just calling additionally i.e. `SalesTax.getSalesTax("CA", "SK")` yourself?

**Comment by maktouch** [comment]
It isn't, no. Without this change, it'll output like

```js
{
  type: 'gst+qst',
  rate: 0.14975,
  area: 'national',
  exchange: 'consumer',
  charge: { direct: true, reverse: false }
}
```

With this change, it'll output 

```js
{
  type: 'gst+qst',
  rate: 0.14975,
  detailed: { gst: 0.05, qst: 0.09975 },
  area: 'national',
  exchange: 'consumer',
  charge: { direct: true, reverse: false }
}
```

While technically `0.14975` is the good rate, in the invoicing part, it needs to be split. 

For getAmountWithSalesTax, it looks like this 

```js
SalesTax.getAmountWithSalesTax("CA", "QC", 100).then(console.log);
```

```js
{
  type: 'gst+qst',
  rate: 0.14975,
  price: 100,
  total: 114.97500000000001,
  area: 'national',
  exchange: 'consumer',
  charge: { direct: true, reverse: false },
  detailed: [
    { type: 'gst', rate: 0.05, amount: 5 },
    { type: 'qst', rate: 0.09975, amount: 9.975000000000001 }
  ]
}
```

It's so we can use the same library for generating invoice + calculating total.

**Comment by valeriansaliou** [comment]
Thanks for your PR. It's agreed on my side, I'll make some reworks and integrate your PR work in a separate commit.

**Comment by valeriansaliou** [comment]
I've integrated your changes manually, coded unit tests as well as added documentation in the README about this new "details" object.

Changes relative to your PR:

- Renamed "detailed" into "details"
- Moved the "details" object type to an array type

(See the README for more on how to use it.)

**Comment by valeriansaliou** [comment]
Closing this as this has been integrated. Thanks a lot for your work! Pushing a new release on NPMJS now, all tests are green.

**Comment by valeriansaliou** [comment]
Released `v2.2.0`. Thanks a ton @maktouch ! https://github.com/valeriansaliou/node-sales-tax/blob/master/CHANGELOG.md#220-2020-06-12

**Comment by maktouch** [comment]
Thanks to you @valeriansaliou. Big fan of Crisp btw. 

Cheers.

**Pull request closed without merging**
