### PR TITLE
feat: remove node-fetch from lib

### PR DESCRIPTION
**Pull request by mlecoq**
I'd like to use this lib on an edge environment (Vercel) and node-fetch has incompatible dependencies 

The goal of this pr is to use node / edge built-in fetch

### CODE REVIEW

**Comment by valeriansaliou** [comment]
I’d like to keep support for legacy NodeJS versions in this library, if possible down to 12 or 14 since it’s still being used in legacy Node production systems, wouldn’t there be a way to selectively import node-fetch for environments that do not have native fetch?

**Comment by adrai** [comment]
https://github.com/lquixada/cross-fetch

**Comment by mlecoq** [comment]
Could we just create a new major version ?

For older version of node, people could still use previous version of the lib


Node v22 has just arrived, node 18 is in lts

**Comment by mlecoq** [comment]
Hi @valeriansaliou , I have update the PR to use `cross-fetch` as suggested by `adrai` and updated minimum node version to `14` (`cross-fetch` has dropped support for 10 and 12)

**Comment by mo** [comment]
I just upgraded to node 22 (soon LTS) and I got a bunch of punycode module errors caused by this dependency chain:
└─┬ sales-tax@2.15.0
  └─┬ node-fetch@2.6.12
    └── whatwg-url@5.0.0

whatwg-url fixed the punycode issue in v9 and node-fetch started to use whatwg-url v9 in the node-fetch v3 release so the punycode error will be gone if sales-tax either removes node-fetch or upgrades to a 3.x version of node-fetch

**Pull request merged**
